create database dbms;
use dbms;
create table happy (link varchar(200));

insert into happy values
("https://youtu.be/DKFS2tDsZRY"),
("https://youtu.be/uCVDd0wMYXk"),
("https://youtu.be/m7CCnowNdQw"),
("https://youtu.be/TeW-BGOQCn4"),
("https://youtu.be/MHi9mKq0slA"),
("https://youtu.be/eZKd1zkvWxo"),
("https://youtu.be/7E5_TpWgXf8"),
("https://youtu.be/wWPY-Qi0aVQ"),
("https://youtu.be/Mzk6KkyxXC8"),
("https://youtu.be/CeYuFSBkkVw"),
("https://youtu.be/y0e6DlfPrYE"),
("https://youtu.be/hJLc-l8FSb0"),
("https://youtu.be/fp7ys8zO1pU"),
("https://youtu.be/RAHIfb2pJDc"),
("https://youtu.be/sQ2Pd-riK-k"),
("https://youtu.be/-fdRyRiL48w"),
("https://youtu.be/e61dKdDBJ2s"),
("https://youtu.be/gm3-m2CFVWM"),
("https://youtu.be/3qiMJt-JBb4"),
("https://youtu.be/hldMjKHGpag"),
("https://youtu.be/2Lk4o4UDSdM"),
("https://youtu.be/5CKrUDzrf4s"),
("https://youtu.be/GtEvysh1654"),
("https://youtu.be/TXGbhniTBrU"),
("https://youtu.be/a5CslyeXmOE");
create table sad (link varchar(200));
insert into sad values
("https://youtu.be/VsJzY12lZos"),
("https://youtu.be/oS07d8Gr4tw"),
("https://youtu.be/FM7MFYoylVs"),
("https://youtu.be/op7wCFw3omI"),
("https://youtu.be/mwL1cohnHNE"),
("https://youtu.be/5VhFX49fU84"),
("https://youtu.be/XbxNtPiCBK8"),
("https://youtu.be/m-1UqKjoet0"),
("https://youtu.be/knlWef-7slc"),
("https://youtu.be/KxnpFKZowcs"),
("https://youtu.be/W0DM5lcj6mw"),
("https://youtu.be/d5GkgVhFeZY"),
("https://youtu.be/p-T6aaRV9HY"),
("https://youtu.be/XSvlIBhpFM8"),
("https://youtu.be/FBuIBaDSOa4"),
("https://youtu.be/PpAartbZJvI"),
("https://youtu.be/sR4UYZPhTXY"),
("https://youtu.be/3W6-WeMisiw"),
("https://youtu.be/bPs0xFd4skY"),
("https://youtu.be/GPvBmcoriNo"),
("https://youtu.be/Mzk6KkyxXC8"),
("https://youtu.be/DynTwKGcEHM"),
("https://youtu.be/KSbwHzlcgs8"),
("https://youtu.be/ytMUjBogO1Q"),
("https://youtu.be/jrYfsCQ-pgk");

